config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # get 'ingredients/index'
  # get 'ingredients/show'
  # get 'ingredients/new'
  # get 'ingredients/create'
  # get 'ingredients/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
  resources :ingredients, only: [:index, :new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :delete_all
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  # before_destroy :clear_doses

  def self.search(query)
    self.find_by_sql("SELECT DISTINCT cocktails.name, cocktails.id FROM cocktails
                      WHERE cocktails.name ILIKE '%#{query}%'
                      UNION
                      SELECT DISTINCT cocktails.name, cocktails.id FROM cocktails
                      JOIN doses ON cocktail_id = cocktails.id
                      JOIN ingredients ON doses.ingredient_id = ingredients.id
                      WHERE ingredients.name ILIKE '%#{query}%'")
  end

  private
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :ingredient, scope: :cocktail

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy, :edit, :update]

  def index
    filter= "'%#{params[:search]}%'"
    @query = params[:search]

    if @query.nil?
      @cocktails = Cocktail.all
    else
      @cocktails = Cocktail.search(@query)
    end
  end

  def show
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path(@cocktail)
    # raise
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  before_action :set_dose, only: [:destroy]

  def new
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
    redirect_to request.referrer
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:destroy]

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<h1>Editing <%= @cocktail.name %></h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Edit cocktail" %>
<% end %>

app/views/cocktails/index.html.erb
<h1>List of cocktails</h1>

<ul>
<% @cocktails.each do |cocktail| %>
  <li> <%=link_to cocktail.name.capitalize, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

<%= link_to "Add new cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Add cocktail" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

<h3>Ingredients:</h3>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li>
      <%= "#{dose.ingredient.name.capitalize}: #{dose.description}" %>
      <%= link_to dose_path(dose), :method => :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </li>
<% end %>
</ul>

<%= link_to "Edit cocktail", edit_cocktail_path(@cocktail) %> |
<%= link_to "Add an ingredient", new_cocktail_dose_path(@cocktail) %> |
<%= link_to "Delete cocktail", cocktail_path(@cocktail), :method => :delete %> |
<%= link_to "Other cocktails", cocktails_path %>

app/views/doses/new.html.erb
Create a new dose

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, as: :select %>
  <%= f.input :description %>
  <%= f.submit "Add ingredient" %>
<% end %>
<br>
<%= link_to "Add new ingredient to list", new_ingredient_path %>

app/views/ingredients/index.html.erb
<h1>List of all ingredients</h1>

<ul>
  <% @ingredients.each do |ingr| %>
    <li>
      <%= ingr.name.capitalize %>
      <%= link_to ingredient_path(ingr), :method => :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Add new ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>Add a new ingredient</h1>

<%= simple_form_for(@ingredient) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Add ingredient" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">

    <%= link_to "All cocktails", cocktails_path %>


    <form class="form-inline" action="/cocktails" method="get">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="search" class="form-control" name="search" value=<%= @query %>>
    <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <%= link_to "All ingredients", ingredients_path %>

</div>